### PR TITLE
Grails3

### PR DESCRIPTION
**Pull request by codeconsole**
This converts this plugin to Grails 3.0.

The only thing remaining to do is convert the 
scripts folder,
webtest folder,
release.sh,
and travis-build.sh

Everything seems to work perfectly.  All plugin dependencies removed (Except Spring Security and mail)

for famfamfam, jquery and jquery-ui,  the plugin assumes that your application bower installed 
jquery, jquery-ui and famfamfam-silk

All assets were convert to the assets pipeline.  The tag library was converted to use the assets pipeline as well.

### CODE REVIEW

**Comment by codeconsole** [comment]
I added .bowerrc and bower.json.  Putting these into any grails project that uses this plugin and then running bower install will automatically install the jquery, jquery-ui, and famfamfam resources into that project.  Alternatively, bower install can be ran on this plugin and these resources will be bundled with the plugin.

**Comment by codeconsole** [comment]
@graemerocher @burtbeckwith This is good to go. Let me know if you want anything else done.  Not too sure how you guys want to handle the travis stuff with grails 3.

**Comment by burtbeckwith** [comment]
Thanks, I'm working on the ACL plugin and this one's next.

**Comment by codeconsole** [comment]
#35

**Comment by burtbeckwith** [comment]
The plugin has been updated - the 3.0.0.M1 release works with Grails 3

**Pull request closed without merging**
